name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: Dobby ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64]
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: osx
          - arch: x86
            os: ubuntu-latest
            cmake_args: -DCMAKE_CXX_FLAGS="-m32 -Os" -DCMAKE_C_FLAGS="-m32 -Os"
          - arch: x64
            os: ubuntu-latest
            cmake_args: -DCMAKE_CXX_FLAGS="-m64 -Os" -DCMAKE_C_FLAGS="-m64 -Os"
          - arch: x86
            os: windows-latest
            cmake_args: -DCMAKE_GENERATOR_PLATFORM=x32 
          - arch: x64
            os: windows-latest
            cmake_args: -DCMAKE_GENERATOR_PLATFORM=x64 -A x64
          - arch: x86
            os: macos-latest
            cmake_args: -DPROJECT_ARCH=i386 -DCMAKE_OSX_ARCHITECTURES=i386 -DCMAKE_EXE_LINKER_FLAGS="-lSystem" -DCMAKE_SHARED_LINKER_FLAGS="-lSystem"
          - arch: x64
            os: macos-latest
            cmake_args: -DCMAKE_OSX_ARCHITECTURES=x86_64
      

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: echo cmake_args
        run: echo '${{ matrix.cmake_args }}'
      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Install 32 bit compiler (ubuntu)
        if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.arch, 'x86')
        run: sudo apt-get install gcc-multilib g++-multilib
      - name: Run CMake
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeListsOrSettingsJson: 'CMakeListsTxtAdvanced'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          #buildWithCMakeArgs: '-- -v'
          cmakeAppendedArgs: ${{ matrix.cmake_args }}
          buildDirectory: '${{ runner.workspace }}/b/Dobby/'
          cmakeBuildType: Release
      - uses: actions/upload-artifact@v2
        with:
          name: dobby-${{ matrix.platform }}-${{ matrix.arch }}
          path: '${{ runner.workspace }}/b/Dobby/'
